# Add informative headers to scanned mail so clients/users can see results.
extended_spam_headers = true;
use = ["x-spamd-bar", "x-spam-level", "x-spam-status", "authentication-results"];
authenticated_headers = ["authentication-results"];
